### ISSUE TITLE
Inventory search does not work in the Bank Items interface

### ISSUE THREAD

**Issue by GTSavvy** [Centias/BankItems#7] opened 2022-12-14 00:06 UTC
If you open up the bank items interface (by clicking the tooltip or other method) and type into the search bar, the Bank Items interface is not searched (i.e. items are not greyed out and search results properly highlighted) but your bag inventory will be properly searched as expected.

Example: 
![image](https://user-images.githubusercontent.com/119644994/207471983-d7aa6656-3143-40b1-9d1b-1f5dab717fd3.png)

**Comment by Centias** [comment] 2022-12-15 06:52
Turns out the fix for this was really easy I had just realized I needed another C_Container with SetItemSearch

**Comment by GTSavvy** [comment] 2022-12-15 23:46
Confirmed search working in 10.0.2.4 (although in game ui shows v10.0.2,2
![image](https://user-images.githubusercontent.com/119644994/207990184-35a06639-4d0b-4571-867a-7907d2e17328.png)

**Comment by Centias** [comment] 2022-12-16 08:02
Confirmed, am idiot who forgets to update TOC file version number.
Updated the file in the release but it shouldn't really affect anything.

**Closed** 2022-12-18 11:15 UTC
